version: 2.1

executors:
  default:
    working_directory: /go/src/github.com/yanolab/atomicop
    docker:
      - image: circleci/golang:1.12-stretch
    environment:
      GO111MODULE: "on"
  test:
    working_directory: /go/src/github.com/yanolab/atomicop
    docker:
      - image: circleci/golang:1.12-stretch
      - image: mysql:5.7
        environment:
          MYSQL_DATABASE: atomicop
          MYSQL_ROOT_PASSWORD: pass
          MYSQL_ROOT_HOST: ""
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      GO111MODULE: "on"

commands:
  restore_pkg_cache:
    steps:
      - restore_cache:
          keys:
            - v1-pkg-cache-{{ checksum "go.sum" }}
            - v1-pkg-cache-

jobs:
  review:
    executor:
      name: default
    steps:
      - checkout
      - restore_pkg_cache
      - run:
          name: Setup reviewdog
          command: |
            curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $(go env GOPATH)/bin
            GO111MODULE=off go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - run:
          name: review
          command: reviewdog -reporter=github-pr-review -diff="git diff master"
  test:
    executor:
      name: test
    steps:
      - checkout
      - restore_pkg_cache
      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 3m
      - run:
          name: test
          command: |
            go run docker/init.go
            go test -v -race ./...

workflows:
  review-and-test:
    jobs:
      - review:
          filters: &default_filter
            branches:
              only: /.*/
      - test:
          filters: *default_filter
