CREATE TABLE IF NOT EXISTS atomicop (
  id         VARCHAR(256) NOT NULL
, state      INT          NOT NULL DEFAULT 0
, attempts   INT          NOT NULL DEFAULT 0
, created_at DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
, updated_at DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
, PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
